### ISSUE TITLE
`Orca` does not work on Windows 

### ISSUE THREAD

**Issue by GegznaV** [plotly/orca#100]
I want to use `orca()` through package **plotly** in **R**. I installed `orca` on Windows 10 following the instructions:

* https://github.com/plotly/orca#installation

All the commands I describe next were called from Command Prompt, not from R. 
Command `orca` did not work. Thus I added `C:\Users\my_pc\AppData\Local\Programs\orca\orca.exe` to the path manually. Now if I write `C:\Users\my_pc\AppData\Local\Programs\orca\orca.exe` in the prompt, it works. But writing command `orca` doesn't. By writing `PATH` I see that the last element is the path to `orca.exe`.

What should I do next to make `orca` work?

**Comment by GegznaV** [comment]
I renamed from `C:\Users\my_pc\AppData\Local\Programs\orca\orca.exe` to `C:\Users\my_pc\AppData\Local\Programs\orca` in PATH variable and it works. Most probably I copied "Target" field instead of "Start in" in point 4 of instructions for Windows (https://github.com/plotly/orca#installation).

**Comment by kaz321123** [comment]
C:\Users\Andrew\Desktop\Pocket Tools\ORCA-0.1.0-win64\ORCA-0.1.0-win64\bin\   See I had to put the last \ in the path, and then it worked.
