### ISSUE TITLE
orca() does not support file paths

### ISSUE THREAD

**Issue by emallickhossain** [plotly/orca#101]
I'm trying to export a static image in R using orca(), but it ignores the file path and just exports it to the current location of the script that I'm running. 

For example, if I run `orca(image, "/images/plot1.png")` from a script located in  `/code/script.R`, it saves it to `/code/plot1.png` instead of where I specified.

**Comment by etpinard** [comment]
I think this has to do with the R wrapper.

Probably best to post on https://github.com/ropensci/plotly/issues/new

**Comment by debarundhar** [comment]
I'm having the same issue on Python 2.7. The filename is correct, but the figure is saved to the current directory instead of in the specified directory.

**Comment by etpinard** [comment]
> I'm having the same issue on Python 2.7. The filename is correct, but the figure is saved to the current directory instead of in the specified directory.

Can you share a code snippet of your attempt?

**Comment by debarundhar** [comment]
Here it is: I am saving two figures to disk, a 2D figure from matplotlib and a 3D figure from Plotly (using Orca). The 2D figure gets successfully saved to `./results/2d/test.png`, while my Plotly figure gets saved to `./test.png` instead of `./results/3d/test.png`
```
save_dir = 'results'
save_fname = 'test'

if save_dir:

        plt.savefig('{}/2d/{}.png'.format(save_dir, save_fname))
        plt.close()

        call(['orca', 'graph', json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder),
              '-o', '{}/3d/{}.png'.format(save_dir, save_fname)])
```

**Comment by etpinard** [comment]
what about:

```py
call(['orca', 'graph', json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder),
              '-d', '{}/3d'.format(save_dir), '-o', '{}.png'.format(save_fname)])
```

?

**Comment by debarundhar** [comment]
@etpinard Yup, that works. Thanks!

**Comment by etpinard** [comment]
Ok great. But yeah 

```py
call(['orca', 'graph', json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder),
              '-o', '{}/3d/{}.png'.format(save_dir, save_fname)])
```

should work too.

Bug confirmed. Thanks for reporting. 

The logic here

https://github.com/plotly/orca/blob/be699d60fd4177a113f2c8c84fe1009c9df9e179/bin/graph.js#L116-L117

doesn't seem quite right.

**Comment by ghtmtt** [comment]
Hi all.. I'm trying to make some tests with Orca.

I get errors in both Linux and Windows (Windows in a Virtual Machine).

The script used is the same as that one in the Readme.md. From a python3 shell:

```
from subprocess import call
import json
import plotly

fig = {"data": [{"y": [1,2,1]}]}
call(['orca', 'graph', json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)])
```
the error is:

```
The following are not valid: graph {"data": [{"y": [1, 2, 1]}]}
```

With Windows I have to change the call to orca with the option `shell=True`, but then I get an exit code = 1 (meaning nothing has been done right?).

Plotly version installed in both system is 2.5.1

Thanks for any hint!

**Comment by etpinard** [comment]
@ghtmtt 

what does

```
> orca --help
```

output in your command prompt?

**Comment by ghtmtt** [comment]
ouch! sorry!! was super super sure call plotly's orca...

is that any future chance to have it shipped together with plotly (so installation with pip)? 

Thanks and sorry again for the noise
