### ISSUE TITLE
running from within R produces no PNG

### ISSUE THREAD

**Issue by mschilli87** [plotly/orca#119]
I am trying to render a 3D plotly plot I made in R statically from different angles as PNG files.
I managed to dump the plotly object to a JSON file but running

```r
system("orca graph /tmp/test.json -o /tmp/model.png")
```

does not produce the PNG file.
It runs for ~3sec and finishes but all it leaves behind is an empty `/tmp/orca-build` directory.

Surprinsingly, running

```sh
orca graph /tmp/test.json -o /tmp/model.png
```

(copy/paste-ed from R, just to be sure) from shell works produces the correct PNG file.

Any clues what is going on?
I want to generate many PNGs to use them as frames for a video, so being able to do this from an R loop would be much more convenient than looping in R to create many JSONs and looping again in shell to convert them all.

**Comment by etpinard** [comment]
Does 

```r
library(plotly)

p <- plot_ly(x = 1:10, y = 1:10, color = 1:10)
b <- plotly_build(p)$x[c("data", "layout")]
json <- plotly:::to_JSON(b)

cmd <- sprintf("orca graph '%s' -o r-export-test.png", json)
system(cmd)
```

as in our [quick start instructions](https://github.com/plotly/orca#quick-start) work for you though?

**Comment by mschilli87** [comment]
@etpinard: Yes it does, but this is a much more basic plot and `orca` finishes basically immediately.
I guess this only occurs when some more heavy lifting is involved.
My JSON is > 3 MB, but it worked 10/10 time from the shell and 0/10 times via `system` from R.

**Comment by etpinard** [comment]
Have you tried the new `orca` function in R 

https://github.com/plotly/orca/pull/94/files

**Comment by mschilli87** [comment]
It throws

```
Error: No mapbox access token found. Obtain a token here
https://www.mapbox.com/help/create-api-access-token/
Once you have a token, assign it to an environment variable 
named 'MAPBOX_TOKEN', for example,
Sys.setenv('MAPBOX_TOKEN' = 'secret token')
```

instead of using my local installation of orca

**Comment by etpinard** [comment]
Are you trying to export a `scattermapbox` graph? If so, then yes you'll need to add the access token to your shell environment.

Now, maybe the R api wants you to have `MAPBOX_TOKEN` set no matter what graph you're trying to export. I don't know., but that would be a question for https://github.com/ropensci/plotly

**Comment by mschilli87** [comment]
But shouldn't command line `orca` run fine when called from within R just like when called from shell? Or is this something I'd have to take up to the base-R devs? :wink:

**Comment by mschilli87** [comment]
This is very weird: Now, I am also not able to get the PNG when running

```sh
orca graph /tmp/test.json -o /tmp/model.png
```

but

```sh
cd /tmp && orca graph test.json -o model.png && cd -
```

works.

So I went ahead and tried

```r
system("cd /tmp && orca graph test.json -o model.png")
```
 and I got the PNG!

---
Should I close this issue and open a new one or just change this issues title to further investigate?

**Comment by etpinard** [comment]
> Should I close this issue and open a new one or just change this issues title to further investigate?

This appears like a duplicate of https://github.com/plotly/orca/issues/101

**Comment by mschilli87** [comment]
I can confirm that I indeed had a `~/model.png` from the 'unsuccessful' runs. :wink:
