### ISSUE TITLE
problems installing seurat; hdf5r installing issues

### ISSUE THREAD

**Issue by chazdm** [plotly/orca#121]
Hello,

I am trying to install Seurat and having troubles with it. I keep getting the error message as follows:

ERROR: dependency ‘hdf5r’ is not available for package ‘Seurat’
* removing ‘/gpfs/home/cdmelloc/anaconda/envs/U87/lib/R/library/Seurat’
Installation failed: Command failed (1)

So I tried installing the hdf5r package, I get the following error:

> install.packages("hdf5r", repos='http://cran.stat.sfu.ca/')
trying URL 'http://cran.stat.sfu.ca/src/contrib/hdf5r_1.0.0.tar.gz'
Content type 'application/x-gzip' length 1623251 bytes (1.5 MB)
==================================================
downloaded 1.5 MB

* installing *source* package ‘hdf5r’ ...
** package ‘hdf5r’ successfully unpacked and MD5 sums checked
checking for a sed that does not truncate output... /bin/sed
checking for gawk... gawk
checking for grep that handles long lines and -e... /usr/bin/grep
checking for gcc... /export/home/cdmelloc/anaconda/envs/U87/bin/x86_64-conda_cos6-linux-gnu-cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /export/home/cdmelloc/anaconda/envs/U87/bin/x86_64-conda_cos6-linux-gnu-cc accepts -g... yes
checking for /export/home/cdmelloc/anaconda/envs/U87/bin/x86_64-conda_cos6-linux-gnu-cc option to accept ISO C89... none needed
checking how to run the C preprocessor... /export/home/cdmelloc/anaconda/envs/U87/bin/x86_64-conda_cos6-linux-gnu-cpp
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for h5cc... /export/home/cdmelloc/anaconda/bin/h5cc
checking for HDF5 libraries... yes (version 1.8.15-patch1)
checking hdf5.h usability... no
checking hdf5.h presence... yes
configure: WARNING: hdf5.h: present but cannot be compiled
configure: WARNING: hdf5.h:     check for missing prerequisite headers?
configure: WARNING: hdf5.h: see the Autoconf documentation
configure: WARNING: hdf5.h:     section "Present But Cannot Be Compiled"
configure: WARNING: hdf5.h: proceeding with the compiler's result
configure: WARNING:     ## -------------------------------- ##
configure: WARNING:     ## Report this to hoeflin@gmail.com ##
configure: WARNING:     ## -------------------------------- ##
checking for hdf5.h... no
checking for H5Fcreate in -lhdf5... no
configure: WARNING: Unable to compile HDF5 test program
checking for hdf5_hl.h... no
checking for H5LTpath_valid in -lhdf5_hl... no
configure: WARNING: Unable to compile HDF5_HL test program
checking for main in -lhdf5_hl... no
checking for matching HDF5 Fortran wrapper... no
Found hdf5 with version: 1.8.15-patch1
checking for ggrep... /usr/bin/grep
checking whether /usr/bin/grep accepts -o... yes
configure: creating ./config.status
config.status: creating src/Makevars
** libs
cp 1_8_14/*.c 1_8_14/*.h .
x86_64-conda_cos6-linux-gnu-cc -I"/export/home/cdmelloc/anaconda/envs/U87/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -I/export/home/cdmelloc/anaconda/envs/U87/include  -D_DEFINE_H5FREE_MEMORY_=0 -D__USE_MINGW_ANSI_STDIO -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/export/home/cdmelloc/anaconda/envs/U87/include -fdebug-prefix-map==/usr/local/src/conda/- -fdebug-prefix-map==/usr/local/src/conda-prefix  -c const_export.c -o const_export.o
In file included from const_export.h:22:0,
                 from const_export.c:23:
global.h:23:10: fatal error: hdf5.h: No such file or directory
 #include <hdf5.h>
          ^~~~~~~~
compilation terminated.
make: *** [/export/home/cdmelloc/anaconda/envs/U87/lib/R/etc/Makeconf:160: const_export.o] Error 1
ERROR: compilation failed for package ‘hdf5r’
* removing ‘/gpfs/home/cdmelloc/anaconda/envs/U87/lib/R/library/hdf5r’

The downloaded source packages are in
        ‘/tmp/RtmpIqqGIl/downloaded_packages’
Warning message:
In install.packages("hdf5r", repos = "http://cran.stat.sfu.ca/") :
  installation of package ‘hdf5r’ had non-zero exit status

I'm new to working with R and would very much appreciate any asistance.

**Comment by etpinard** [comment]
This must be a mistake. This bug report makes no mention of orca nor plotly.
