### ISSUE TITLE
orca CLI does not recognize directory; saves everything in current dir

### ISSUE THREAD

**Issue by pbreheny** [plotly/orca#123]
The basic example given in the README does not work correctly if a filename with a path is specified:

```
orca graph '{ "data": [{"y": [1,2,1]}] }' -o tmp/fig.png
```

This creates 'fig.png' in the current directory, not in 'tmp'.

This is presumably related to #101, but just wanted to point out that it isn't an R/python API issue; it happens when you use orca directly as well.

Version info: 1.1.0 installed via npm.

**Comment by etpinard** [comment]
duplicate of https://github.com/plotly/orca/issues/101
