### ISSUE TITLE
Should we start diff testing PDF exports?

### ISSUE THREAD

**Issue by etpinard** [plotly/orca#13]
It might worth spending some time adding pdf diff test to our suite (e.g. using [`diffpdf`](http://manpages.ubuntu.com/manpages/trusty/man1/diffpdf.1.html)). I suspect once `plotly-image-exporter` is out, pdf exports will be pretty popular.

**Comment by antoinerg** [comment]
With the introduction of `test-image` in PR https://github.com/plotly/orca/pull/222, we now do image diff for all the image formats that Orca supports. I think we can now close this one.
