### ISSUE TITLE
orca can not export large plotly

### ISSUE THREAD

**Issue by zerlia** [plotly/orca#138]
Hi ~
When I use orca(p, file = "pp.png"), If the plotly object p is small, it is OK. But if p contain many data inside or too complex, then R will return Error as follow:

**Error in process_initialize(self, private, command, args, stdin, stdout,  : 
  processx error, create process: #206 文件名或扩展名太长。
 at 'win/processx.c:1039'**

My computer is Window 7 64bit and R version is 3.5.1

In Google I just find it may be the limit of CMD on Windows. but how to solve this?

I will appreciate any help.

**Comment by etpinard** [comment]
Hmm, this appears like a problem with the R wrapper. 

Have you tried upgrading to their version available on CRAN?

**Comment by alberduris** [comment]
> Hmm, this appears like a problem with the R wrapper.
> 
> Have you tried upgrading to the latest version available on CRAN?

Yes, but does not solve the problem. 

In fact my error is `process_initialize not found`

`

**Comment by jonmmease** [comment]
@cpsievert, have you seen this error before?

**Comment by dspires** [comment]
Hi, supers.

I installed the GitHub version using `devtools::install_github('ropensci/plotly')` but the same error still occurs.

If I try to use `export`:

`> export(h, file = "output/heatmap-down.png")
1   0x1b67967 /home/pires/bin/phantomjs() [0x1b67967]
2   0x9fed7a /home/pires/bin/phantomjs() [0x9fed7a]
3   0xa049ec /home/pires/bin/phantomjs() [0xa049ec]
4   0x1277ba6 /home/pires/bin/phantomjs() [0x1277ba6]
5   0x8de704 /home/pires/bin/phantomjs() [0x8de704]
6   0x13056d2 /home/pires/bin/phantomjs() [0x13056d2]
7   0x16ef717 /home/pires/bin/phantomjs() [0x16ef717]
8   0x175e2de /home/pires/bin/phantomjs() [0x175e2de]
9   0x176341e /home/pires/bin/phantomjs() [0x176341e]
10  0xd57a49 /home/pires/bin/phantomjs() [0xd57a49]
11  0x7fe7756ca0e5 [0x7fe7756ca0e5]
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
Error in webshot::webshot(f, file, ...) :
  webshot.js returned failure value: -11
In addition: Warning message:
'export' is deprecated.
Use 'orca' instead.
See help("Deprecated")
`

If I try to use `orca`:

`> orca(h, "output/heatmap-down.png")
Error in process_initialize(self, private, command, args, stdin, stdout,  :
  processx error: 'Argument list too long' at unix/processx.c:423
`

Do you have any idea on how to solve this?

Thanks in advance.

--
David da Silva Pires

**Comment by cpsievert** [comment]
> Do you have any idea on how to solve this?

I might be able to help, but please open an issue here, include your `devtools::session_info()`, and a reproducible example

https://github.com/ropensci/plotly/issues/new

**Comment by etpinard** [comment]
This appears to be a problem with the R wrapper. Closing (for now).
