### ISSUE TITLE
Pure python package? 

### ISSUE THREAD

**Issue by romelgomez** [plotly/orca#141]
I attempt to integrate orca to AWS Lambda function, and orca has dependencies in packages of NPM, that need to be installed globally. 

I attempt to install the packages locally `npm install electron@1.8.4 orca`, to see if work, and then put the folder node_modules in the .zip build, but not work for me. 

Any idea how to tackle this.

**Comment by etpinard** [comment]
Would using `conda` work for you?

https://github.com/plotly/orca#method-1-conda

**Comment by romelgomez** [comment]
Well, it looks like that will work, but the lambda has a limit of [50MB](https://docs.aws.amazon.com/lambda/latest/dg/limits.html) and the node_modules folder after installing electron@1.8.4 orca weight 132MB, also test this hypothesis will change all the build process set by the template that we have to use.

I test the online API, the simple example:  

```
import plotly
plotly.tools.set_credentials_file(username='*******', api_key='********')
import plotly.plotly as py
import plotly.graph_objs as go

        trace0 = go.Scatter(
            x=[1, 2, 3, 4],
            y=[10, 15, 13, 17]
        )
        trace1 = go.Scatter(
            x=[1, 2, 3, 4],
            y=[16, 5, 11, 9]
        )
        data = [trace0, trace1]

        a = py.plot(data, filename = 'basic-line', auto_open=True)
        logger.info(a)
```

That return `https://plot.ly/~user/0`, It will nice to have a dict or object that contain the plot in differents formats e.g: 

```
{
img: { png: 'url', jpg: 'url' }
link: https://plot.ly/~user/0
etc...
}
```   
To later save on some cloud, or use directly
