### ISSUE TITLE
Error when trying to write multi-page PDF file

### ISSUE THREAD

**Issue by slishak** [plotly/orca#143]
I appreciate that this is not necessarily an issue with Plotly or Orca, but I'm trying to use PyPDF2 to write a multiple page PDF file, as per the following Python example:

```python
import plotly.io as pio
import plotly.graph_objs as go
import io
from PyPDF2 import PdfFileMerger
import numpy as np


def make_figure():
    """Function to make random figure"""
    x = np.linspace(0, 10, 100)
    y = np.random.randint(1, 100, 100)

    trace = go.Scatter(x=x, y=y, mode='markers')
    return go.Figure(data=[trace])


use_stream = False
merger = PdfFileMerger()

for i in range(3):
    print('Page {}'.format(i+1))

    if use_stream:
        pdf_file = io.BytesIO()
    else:
        pdf_file = '{}.pdf'.format(i)

    pio.write_image(make_figure(), pdf_file, 'pdf')

    if use_stream:
        pdf_file.seek(0)
    merger.append(pdf_file)

merger.write('merged.pdf')

```

All of the individual PDFs are written correctly, but PyPDF2 fails to merge them with the following error:
`PyPDF2.utils.PdfReadError: Multiple definitions in dictionary at byte 0x8f0 for key /Type`

This happens whether I write the files to disk or use an in-memory BytesIO stream.

Just wondering whether you think this is an issue with PyPDF2 or with Orca? I'm leaning towards thinking there's actually a bug in both, because PyPDF2 has this open issue: https://github.com/mstamy2/PyPDF2/issues/325, but looking in the raw bytes of the PDF files written by Orca I can see repeated `/Type /ExtGState` lines which are maybe the root cause.

I'd also be interested in being able to append a new page to a PDF document directly from Plotly/Orca so that I don't have to use another library!

**Comment by slishak** [comment]
Yes, that seems to work fine. Although I found out that it also works if you disable `strict` mode in `PyPDF2.PdfFileMerger` so currently this issue isn't actually limiting me - I just get a lot of console warnings spitted out now!

**Comment by etpinard** [comment]
Thanks for the reply. It sounds like orca PDF exports are _ok_.

I'll close this issue. We aren't planning on adding multi-page (multi-graphs) exports for the moment.

**Comment by slishak** [comment]
Agreed that they're "OK" and happy to have this issue closed - although looking at what's written in the  issue linked in the original post, they do technically seem to be violating the PDF standard!
