### ISSUE TITLE
rstudio not recognizing orca cmd tools

### ISSUE THREAD

**Issue by dschneiderch** [plotly/orca#155]
i'm trying to download a figure from a rshiny app that displays a plotly figure. rstudio throws an error 

```
Warning: Error in : The orca command-line utility is required for this functionality.
Please follow the installation instructions here -- https://github.com/plotly/orca#installation
  [No stack trace available]
```

but orca is in the path.  see image
![image](https://user-images.githubusercontent.com/7461221/49167634-9de37a00-f2ea-11e8-8211-c14dd1e408fc.png)

Im running WIndows 10 with the latest Rstudio v1.1.463. the app developer suggested I try a different plotly version so after I tried plotly on cran (plotly_4.8.0) I got the same result with plotly from devtools::install_github("ropensci/plotly") plotly_4.8.0.9000

any suggestions?

EDIT:
sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.1 tools_3.5.1    yaml_2.2.0

**Comment by jonmmease** [comment]
Hi @dschneiderch ,

Thanks for reaching out, can you try the suggestions in https://github.com/plotly/orca/issues/120#issuecomment-424000634?

**Comment by dschneiderch** [comment]
oddly enough  i opened everything up (computer was shut down over the weekend) and it worked*, but I will keep that in mind. Thanks.

* it worked as expected ( download of plot.png) from an external viewer (browser) but when using the internal rstudio viewer i get a file called download_plot without an extension. renaming it to png allows it to open. i believe the internal R function inside the app is called download_plot if that helps. my understanding is this is a known issue though.
