### ISSUE TITLE
Terminate xvfb-run processes started with -a?

### ISSUE THREAD

**Issue by williamhakim10** [plotly/orca#158]
The current guidance for running headlessly is to do something like:

```xvfb-run -a /path/to/AppImage...``` as in the readme.

This works well, except that I am using a daemon (Celery, to be precise) to invoke orca. If the daemon is ever restarted (in Celery's case, this can be all sorts of things such as missed heartbeats or a new deployment), then a new xvfb instance is created (rather than using the currently existing one). Over time, this leads to a large number of xvfb processes being spawned.

Is there a way to reap the xvfb instance after orca is done? Or is there an alternative, better approach?

**Comment by jonmmease** [comment]
Hi @williamhakim10, are you calling the `xvfb-run` script from Python using plotly.py's `plotly.io.write_image`? Or calling orca directly using a subprocess?

In any case, an alternative to using `xvfb-run` is to startup a single long-running Xvfb server and set the `DISPLAY` environment variable to the server's port.  Basically run something like this...

```
Xvfb :99 &
export DISPLAY=:99
```

before calling `orca`, and then call orca directly *without* using `xvfb-run`.  The disadvantage of this approach is that you are responsible somehow shutting down the Xvfb instance when you're done, but if you have a long-running daemon process then perhaps you'll want to keep this Xvfb instance running all the time anyway. Here's some useful info http://elementalselenium.com/tips/38-headless.

Hope that helps!

**Comment by williamhakim10** [comment]
@jonmmease thanks for your reply - I more than appreciate the help! This sounds like a good solution (I will probably want to keep a bunch of Xvfb instances open simultaneously - as Celery is a task queue, but that's another matter). In the meantime I simply added a `kill_xvfb` function to my Celery init script, which can be called whenever the daemon stops for some reason (each Celery worker seems to be keeping its own xvfb instance started with `xvfb-run` open indefinitely)

```
kill_xvfb () {
    local xvfb_pids=`ps aux | grep tmp/xvfb-run | grep -v grep | awk '{print $2}'`
    if [ "$xvfb_pids" != "" ]; then
        echo "Killing the following xvfb processes: $xvfb_pids"
        sudo kill $xvfb_pids
    else
        echo "No xvfb processes to kill"
    fi
}
```

**Comment by jonmmease** [comment]
Great, thanks @williamhakim10. Do you mind if we close now?

**Comment by williamhakim10** [comment]
Yes, I'll close it. Thanks you for your advice!
