### ISSUE TITLE
Pyinstaller using orca

### ISSUE THREAD

**Issue by XavierdeBondt** [plotly/orca#161]
When attempting to use [Pyinstaller](https://www.pyinstaller.org/) and creating a custom [.spec file](https://pyinstaller.readthedocs.io/en/v3.3.1/spec-files.html) which ensures it encludes orca as shown here (since it seems incompatible with pyinstaller)
```
             datas=[('C:/My/Path/to/orca/', './orca/')],
             hiddenimports=['orca']
```
Note that

- It includes the orca folder in the dist folder when using pyinstaller
- This orca folder is the folder that includes orca.exe

The executable tells the user when running it on a pc **without orca (or python) installed** that orca has to be installed (so the pyinstaller failed..).   
Is it that orca is impossible to be used with pyinstaller or am I doing something wrong?

**Comment by jonmmease** [comment]
Closing to move discussion to https://community.plot.ly/t/pyinstaller-with-plotly-orca-and-psutils-not-working/16324.
