### ISSUE TITLE
Can't export graphs [Win10]

### ISSUE THREAD

**Issue by chrispahm** [plotly/orca#162]
Hey there,
I tried following command line example from your README:
```
orca graph '{ "data": [{"y": [1,2,1]}] }' -o fig.png
```
which returns the following message:
```
done with code 1 in 1.79 ms - failed or incomplete task(s)
``` 
I'm running orca `1.1.1` on a Windows 10 x64 machine (using CMD). 
When using the `--verbose` flag, it orca tells me that it has issues parsing the JSON:
```
C:\Users\pahmeyer>orca graph '{ "data": [{"y": [1,2,1]}] }' -o fig.png --verbose

export error 422 for fig_0 - json parse error
  undefined
export error 422 for fig_1 - json parse error
  undefined
export error 422 for fig_2 - json parse error
  undefined
export error 422 for fig_3 - json parse error
  undefined
export error 422 for fig_4 - json parse error
  undefined

done with code 1 in 3.54 ms - failed or incomplete task(s)
```

Calling the exact same JSON from a file, the output is generated as expected:
```
C:\Users\pahmeyer>orca graph plot.json  -o fig.png --verbose

exported fig, in 183.006817 ms

done with code 0 in 183.93 ms - all task(s) completed
```

Thought this might be of interest for you.

For anyone experiencing this issue as well, I wrote a couple lines in R to circumvent the issue for now:
```r
b <- plotly_build(p)$x[c("data", "layout")]
json <- plotly:::to_JSON(b)
write(json, file = "output.json")
system("orca graph output.json -o output.pdf --format pdf")
file.remove("output.json")
```

**Comment by etpinard** [comment]
I suspect

```
> orca graph '{ "data": [{"y": [1,2,1]}] }' -o fig.png --verbose
```

isn't valid in the Windows command prompt. We must have the wrong combination of `'` and `"` that would make orca consider `'{ "data": [{"y": [1,2,1]}] }'` as one string to JSON-parse. 

Thanks very much for bringing this up! Can a Windows dev help us out?

**Comment by chrispahm** [comment]
Good call! 
I found a [post on stackoverflow](https://stackoverflow.com/questions/28648473/windows-curl-with-json-data-on-the-command-line) describing that Windows `cmd` does not support strings with single quotes. The correct input (in this case) should then look like this:
```
orca graph "{ \"data\": [{\"y\": [1,2,1]}] }" -o fig.png --verbose
```
I just tested this and it works fine. Do you want me to add a line to the readme (as a short notice for Windows `cmd` users) and do a PR?

**Comment by etpinard** [comment]
> Do you want me to add a line to the readme (as a short notice for Windows `cmd` users) and do a PR?

That would be amazing!

**Comment by chrispahm** [comment]
see #167

**Comment by etpinard** [comment]
done in #167
