### ISSUE TITLE
orca --help shows nothing after several .deb files installations, and error when pio.write_image to a linux local path

### ISSUE THREAD

**Issue by ivymichael** [plotly/orca#169]
### Environment

Python: Anaconda Python 3.6.5
Server: Ubuntu server 16.04.03 LTS **without internet access**
Plotly: 3.4.2
orca: v1.1.1

Dear developers,

I install the plotly-orca based on the github page Linux part, after I make the soft link,
here is what I got when type `which orca`
```
(venv) root@CNBEH-REPORT-P21:/var/www/FlaskApp# which orca
/usr/bin/orca
(venv) root@CNBEH-REPORT-P21:/var/www/FlaskApp#
```
And then `orca --help` I got
```
orca: error while loading shared libraries: libgtk-x11-2.0.so.0:
cannot open shared object file: No such file or directory
```
Following the official instructions,  considering this is an offline machine, I download the` libgtk2.0-0` and `libgconf-2-4` related packs and its dependencies from Ubuntu packages site and install manually, after the installation I type` orca --help`, I got similar problems as below subsequently, 
```
(venv) root@CNBEH-REPORT-P21:/var/www/FlaskApp/aptfiles# orca --help
desktop-file-install is missing. Skipping /tmp/.mount_orcabFa99D/AppRun.
```
```
(venv) root@CNBEH-REPORT-P21:/var/www/FlaskApp/aptfiles# orca --help
xdg-icon-resource is missing. Skipping /tmp/.mount_orcaKm8kbQ/AppRun.
```
```
(venv) root@CNBEH-REPORT-P21:/var/www/FlaskApp/aptfiles# orca --help
/tmp/.mount_orca6U2gbA/AppRun: line 206: gtk-update-icon-cache: command not found
```

then I install the `desktop-file-utils`,  `xdg-utils`, and `libgtk2.0-bin` based on system indications.

Finally, when I type `orca --help`, I got nothing comes out surprisingly.
```
root@CNBEH-REPORT-P21:/var/www/FlaskApp# orca --help
root@CNBEH-REPORT-P21:/var/www/FlaskApp#
```

I thought it might work, then I try to use  `plotly.io.write_image` to a local path within a Flask application, but I got the error below:
 ```
  File "/var/www/FlaskApp/FlaskApp/Quality_Development/routes.py", line 82, in spec_boxplot, referer: http://149.197.121.16/qd/boxplot
     pio.write_image(plot_fig, example_dir + '/spec_df/fig1.jpeg'), referer: http://149.197.121.16/qd/boxplot
   File "/var/www/FlaskApp/FlaskApp/venv/lib/python3.6/site-packages/plotly-3.4.2-py3.6.egg/plotly/io/_orca.py", line 1485, in write_image, referer: http://149.197.121.16/qd/boxplot
     validate=validate), referer: http://149.197.121.16/qd/boxplot
   File "/var/www/FlaskApp/FlaskApp/venv/lib/python3.6/site-packages/plotly-3.4.2-py3.6.egg/plotly/io/_orca.py", line 1267, in to_image, referer: http://149.197.121.16/qd/boxplot
     ensure_server(), referer: http://149.197.121.16/qd/boxplot
   File "/var/www/FlaskApp/FlaskApp/venv/lib/python3.6/site-packages/plotly-3.4.2-py3.6.egg/plotly/io/_orca.py", line 1137, in ensure_server, referer: http://149.197.121.16/qd/boxplot
     validate_executable(), referer: http://149.197.121.16/qd/boxplot
   File "/var/www/FlaskApp/FlaskApp/venv/lib/python3.6/site-packages/plotly-3.4.2-py3.6.egg/plotly/io/_orca.py", line 969, in validate_executable, referer: http://149.197.121.16/qd/boxplot
     raise ValueError(err_msg), referer: http://149.197.121.16/qd/boxplot
 ValueError: , referer: http://149.197.121.16/qd/boxplot
 The orca executable is required in order to export figures as static images,, referer: http://149.197.121.16/qd/boxplot
 but the executable that was found at '/usr/bin/orca', referer: http://149.197.121.16/qd/boxplot
does not seem to be a valid plotly orca executable. Please refer to the end of, referer:
this message for details on what went wrong., referer: http://149.197.121.16/qd/boxplot
, referer: http://149.197.121.16/qd/boxplot
```

I even install the xvfb packages wishing it will work, it turns out the same. :(
Can someone help? Thank you!

**Comment by antoinerg** [comment]
@ivymichael Did you try running:
`xvfb-run -a orca --help`

**Comment by ivymichael** [comment]
Hi @antoinerg 
I got the below response,
```
root@CNBEH-REPORT-P21:/var/www/FlaskApp/aptfiles# xvfb-run -a orca --help
Plotly's image-exporting utilities

  Usage: orca [--version] [--help] <command> [<args>]

  Available commands:
  - graph [or plotly-graph, plotly_graph]
    Generates an image of plotly graph from inputted plotly.js JSON attributes.
    For more info, run `orca graph --help`.
  - serve [or server]
    Boots up a server with one route per available export component
    For more info, run `orca serve --help`.

root@CNBEH-REPORT-P21:/var/www/FlaskApp/aptfiles#
```
Seems got some progress! But doesn`t work for Flask application?
Should I create a orca.sh with below content?
```
#!/bin/bash
xvfb-run -a /var/www/FlaskApp/orca/orca-1.1.1-x86_64.AppImage "$@"
```
Then I need to do:
1. put this orca.sh to /usr/bin
2. `ln -s /usr/bin/orca.sh /usr/bin/orca`
Is it right?

**Comment by antoinerg** [comment]
It's a little bit hard for me to help you debug this problem but since it seems like you're building a webapp, did you consider running Orca as a server and using its HTTP api from Flask? 

This way you could start Orca with `xvfb-run -a orca serve --verbose --port 9091` which seems to work for you. Then, from Flask simply send the JSON of the figure you want to render with an HTTP POST request at localhost:9091! The Orca server will return your figure in PNG format :)

**Comment by ivymichael** [comment]
Hi @antoinerg,
Thank you very much! I manage the script problem, I shouldn`t copy orca.sh from window to Linux, when I create it originally from Linux, the link works.

However, when calling the pio.write_image() function within Flask app, the request holds on forever with no page response, anyhow, I`ll try to tweak it more to see further possibilities, and also thanks for your suggestion, I`ll definitely try!

**Comment by ivymichael** [comment]
Hi @antoinerg 
I tried the server command you mentioned, then I got the response below and seems the system is hanging there, no more response. And I have to ctrl + c to stop it.
```
root@CNBEH-REPORT-P21:~# xvfb-run -a orca serve --verbose --port 9091
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
{"severity":"ERROR","textPayload":"gpu process crashed - false"}
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
{"severity":"ERROR","textPayload":"gpu process crashed - false"}
{"severity":"ERROR","textPayload":"gpu process crashed - false"}
{"severity":"ERROR","textPayload":"gpu process crashed - false"}
{"severity":"ERROR","textPayload":"gpu process crashed - false"}
{"severity":"ERROR","textPayload":"gpu process crashed - false"}
```
Am I missing any thing in Ubuntu side?

**Comment by antoinerg** [comment]
It looks like you're missing an OpenGL library. Do you have a working graphical environment? Maybe try to install Mesa 3D library.

Also, are you running Docker? Would you rather have Orca packaged in a Docker container?

**Comment by ivymichael** [comment]
@antoinerg Sorry for the late reply, I`ve been traveling for last few days.
I`m using company internal virutal Linux server, it seems that we don`t have the physical graphical card, is Orca compatible with such situation?
Never tried docker, will it break my current non-docker apache2 web-app-server setup?

```
root@CNBEH-REPORT-P21:~# lspci  | grep -i vga
00:0f.0 VGA compatible controller: VMware SVGA II Adapter
root@CNBEH-REPORT-P21:~# ^C
root@CNBEH-REPORT-P21:~# lspci -v -s 00:0f.0
00:0f.0 VGA compatible controller: VMware SVGA II Adapter (prog-if 00 [VGA contr                                                                                        oller])
        Subsystem: VMware SVGA II Adapter
        Flags: bus master, medium devsel, latency 64, IRQ 16
        I/O ports at 1070 [size=16]
        Memory at e8000000 (32-bit, prefetchable) [size=128M]
        Memory at fe000000 (32-bit, non-prefetchable) [size=8M]
        [virtual] Expansion ROM at c0200000 [disabled] [size=32K]
        Capabilities: [40] Vendor Specific Information: Len=00 <?>
        Capabilities: [44] PCI Advanced Features
        Kernel driver in use: vmwgfx
        Kernel modules: vmwgfx

root@CNBEH-REPORT-P21:~#
```

**Comment by antoinerg** [comment]
No worries @ivymichael!

Yes Orca should work in that situation by running a software implementation of OpenGL such as the ones included in Mesa3D. Rendering 3D figures will take a little bit longer but it will work. 

Also, you may not be aware of this but plot.ly is hosting a fleet of Orcas in the cloud which can be used [with a simple HTTP API](https://api.plot.ly).

Finally, Docker shouldn't break anything and would allow you to run Orca in a container isolated from your host with its own filesystem. This we can run the same container on different machines and get the same results (somewhat). However, installing Docker requires `root` privilege on the machine which you may not have access to.

Please let me know which option is more appropriate for your project :)

**Comment by ivymichael** [comment]
Dear @antoinerg,

Due to firewall issue, the Linux server has no access to the public internet, the HTTP API will not work here I think, however, I do have root privilege for this server.

I\`ll first try to install Mesa3D library and try one more time rendering plotly figure through Orca, for Docker flow, is there any simple deployment tutorial, I want to learn about that, sounds very cool!

Thanks!

**Comment by antoinerg** [comment]
Sounds good @ivymichael ! 

Yes there are tons of Docker tutorials online. Installation can be as straightforward to install on Linux as outlined at https://github.com/docker/docker-install.
