### ISSUE TITLE
Intermittent CI Test Failure: svn: E175002: 504 'Gateway Timeout' 

### ISSUE THREAD

**Issue by BRONSOLO** [plotly/orca#172]
Intermittent test failure: 

```
svn: E175002: Unexpected HTTP status 504 'Gateway Timeout' on '/plotly/plotly.js.git/!svn/bc/30700/trunk/dist'
```

**Comment by BRONSOLO** [comment]
https://circleci.com/gh/plotly/orca/2441?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by BRONSOLO** [comment]
Hit this in: https://github.com/plotly/orca/pull/151

**Comment by antoinerg** [comment]
Now that we have docker layer caching in CircleCI, this error hasn't come up in a while. I will close it for now.
