### ISSUE TITLE
chromium vs google-chrome-stable

### ISSUE THREAD

**Issue by TiemenSch** [plotly/orca#185]
I noticed that the install instructions include quite an elaborate method of installing ``google-chrome-stable`` by adding Google's repository (and keys) before installing. 

Wouldn't it already be sufficient to just install ``chromium-browser`` from the Linux distro's default package manager?

I even experimented with installing the bare dependencies orca named in it's error messages, but suspect that could become problematic down the road.

**Comment by antoinerg** [comment]
> I noticed that the install instructions include quite an elaborate method of installing google-chrome-stable by adding Google's repository (and keys) before installing.

Are you referring to this instruction: https://github.com/plotly/orca/blob/master/README.md#linux-troubleshooting-cannot-open-shared-object ? 

> Wouldn't it already be sufficient to just install chromium-browser from the Linux distro's default package manager?

I think you are right that `chromium-browser` is sufficient and probably even more appropriate since that's what Electron uses.

**Comment by Nikolai-Hlubek** [comment]
+1 for updating the readme. 

The way IT departments in coorporations usually work is, they give you a virtual server that has access to an offline copy of your linux distribution but no further internet access.

So for me in this scenario using CentOS
> sudo yum install chromedriver chromium xorg-x11-server-Xvfb
worked. While downloading google-chrome-stable would have been some extra task.
