### ISSUE TITLE
Add Docker in installation methods

### ISSUE THREAD

**Issue by antoinerg** [plotly/orca#187]
I think we should advertise our Docker images in the installation methods as Docker is getting more and more popular and *should* solve all the problems related to missing dependencies or misconfiguration.

**Comment by etpinard** [comment]
Good idea! We could either upload a docker image for each of our releases alongside the mac/windows/linux executables:

![image](https://user-images.githubusercontent.com/6675409/51118711-0923d580-17df-11e9-9b89-423784383e96.png)

or just provide a link to quay,io (are those public links?) in the README.

cc https://github.com/plotly/orca/issues/178

**Comment by austinbutler** [comment]
Having it available in the Docker Hub would be great. I saw the somewhat convoluted possible install options in the README and at first thought those were the only options. Then I noticed there's a Dockerfile in the deployment folder in this repo, but even then since it's not documented figured it wouldn't be good to rely on it.

**Comment by etpinard** [comment]
Good point by @antoinerg in https://github.com/plotly/orca/pull/190

> For #187, we may want to write a new Dockerfile aimed at offline use without streambed plotly.js but the public bundle.

where I'd say we _should_ add another Dockerfile!

**Comment by antoinerg** [comment]
> Having it available in the Docker Hub would be great.

@austinbutler Is there something special about Docker Hub or would any other Docker registries fit your needs? We were thinking of using quay.io instead. You can pull from it the same way you pull from Docker Hub.

**Comment by austinbutler** [comment]
Quay would be fine, too. But in terms of visibility Docker Hub is just where I default to when looking for images.

**Comment by etpinard** [comment]
> Can we start it from the most recent LTS version of Ubuntu

yes please.

> I could reuse the ones I made many when I worked on delivering

sure.

**Comment by PedroRegisPOAR** [comment]
I would love to see Docker images to run this!

I have a question, @antoinerg I am not sure if I am in the right place, but as an user I would love to use full `plotly.py` functionalities, that includes `orca`, in an Docker image. Who may provide a way to do this? The [plotly.py](https://github.com/plotly/plotly.py) or the `orca` repository?

I guess that for most users, like me, would expect to have a way do install all `plotly.py` stuff, that includes `orca`, from a Python official base image. Is here the right place to talk about this?

I think if `orca` provide a way to build an image it is going to help to build a image for all `plotly.py` stuff.

I have been trying to do so for some time (many hours spent), but no luck. And while searching to see if someone has done a image, I could find many people trying to do that and failing too. A list of some links that I've saved:

From plotly community:
[Plotly-Orca and Docker](https://community.plot.ly/t/plotly-orca-and-docker/17892)
[Error to locate Orca](https://community.plot.ly/t/error-to-locate-orca/16729)

From stackoverflow:
[Docker and Plotly](https://stackoverflow.com/questions/54112336/docker-and-plotly)
[How to Build a Docker Python Image with Plotly?](https://stackoverflow.com/questions/52174012/how-to-build-a-docker-python-image-with-plotly?rq=1)

From a russian guy: [R plotly orca](http://qaru.site/questions/16741399/r-plotly-error-no-mapbox-access-token-found
)

An interesting image that I found is [this](https://hub.docker.com/r/cpsievert/plotly-orca/dockerfile) for the R stuff (I am not R user so is not clear to me what that image does).

**Comment by gpernelle** [comment]
Are there already some documents that could help build a docker image than runs python plotly and orca?
Or a docker image already built?

**Comment by scjody** [comment]
I just became aware of this issue. 👋

https://quay.io/repository/plotly/image-exporter?tab=info is a public Quay repo that holds Orca images for every successful CircleCI `test-and-push` (one is attempted on every push to this GitHub repo). This is, and was always intended to be public.

We should probably rename the repo to avoid confusion (this project wasn't _always_ called "orca"), but other than that is there anything else needed here?

**Comment by antoinerg** [comment]
> We should probably rename the repo to avoid confusion (this project wasn't always called "orca"),

I agree

> , but other than that is there anything else needed here?

As of right now, our Docker images `quay.io/plotly/image-exporter:master` have an entrypoing that starts an Orca server that can be queried by a simple HTTP API. That's very cool and we should advertise that this feature is available today.

However, I think we should also support running Orca as a command-line tool as it does in a normal desktop installation. For example, a user should be able to bind-mount a folder and run the equivalent of `orca graph`:
```bash
$ docker run -i -v $(pwd):$(pwd) -w $(pwd) \
      antoinerg/orca-reproducible graph --verbose myfigure.json
exported myfigure, in 1158.483293 ms
```
or pipe the figure to the STDIN of the process
```bash
cat myfigure.json | docker run -i antoinerg/orca-reproducible graph --verbose > myfigure.png
```
To make this happen, we would need to slightly modify the Dockerfile's `ENTRYPOINT` to enable both use cases.

cc @scjody

**Comment by cedricyau** [comment]
@antoinerg Thanks for uploading the `antoinerg/orca-reproducible` Docker Image to DockerHub.  By any chance, have you published the DockerFile anywhere?  I found it really useful to get around all my Ubuntu Server installation issues and would like to see if I could use it load JSON and publish images to S3 with AWS Batch.

**Comment by antoinerg** [comment]
Thank you @cedricyau for your interest in plotly!

> @antoinerg Thanks for uploading the `antoinerg/orca-reproducible` Docker Image to DockerHub. By any chance, have you published the DockerFile anywhere?

Not yet, sorry!

> I found it really useful to get around all my Ubuntu Server installation issues

Great to hear this! The plan is to have an official Docker image for Orca very soon! (WIP in branch [docker-release](https://github.com/plotly/orca/tree/docker-release)) 

>  and would like to see if I could use it load JSON and publish images to S3 with AWS Batch.

I am not familiar with AWS Batch. Do you need to run Orca as command-line tool or can you run it as a HTTP API server?

**Comment by cedricyau** [comment]
I would need to run `orca` as a command-line tool.  My goal is to have this run serverless.  So we can leave the system "off" most of the time and only run it when we need it.

**Comment by antoinerg** [comment]
@cedricyau I opened a PR https://github.com/plotly/orca/pull/222 which may be of interest to you.

Please note that `antoinerg/orca-reproducible` was meant to achieve reproducible output from machine to machine down to every pixel. This is not something most people care about since the differences can be tiny. The downside is that it uses a software implementation of OpenGL to achieve this and it is rather slow. The upside of course is that an input can only be associated to one output regardless of the hardware you're using. This is actually a bold claim so it needs to be tested further. I hope to roll in a `--reproducible` or `--softwareRendering` flag into the offical Docker image but that will have to wait a little bit.

**Comment by slfan2013** [comment]
> As of right now, our Docker images `quay.io/plotly/image-exporter:master` have an entrypoing that starts an Orca server that can be queried using a simple HTTP API.

Hello @antoinerg , I found using HTTP API to call `orca` really useful for me. I wonder can you please illustrate how to use HTTP API to export svg plots?

Suppose I have a port with url running the orca `http://metda_plotly:9091`. What would be the corresponding command (or code) for `$ orca graph '{ "data": [{"y": [1,2,1]}] }' -o fig.png`? Is it `$ docker run -i quay.io/plotly/orca graph '{ "data": [{"y": [1,2,1]}] }' -o fig.png`?

**Comment by antoinerg** [comment]
@slfan2013 glad to know it is useful for you!

Instead of POSTing a JSON of your figure directy to your endpoint, wrap it in another object with:
```json
{
  "format": "svg",
  "figure": "... your figure"
}
```
as described there: https://github.com/plotly/orca/blob/f40962271ce901492513115854cceb45977448eb/src/component/plotly-graph/parse.js#L12-L35

**Comment by antoinerg** [comment]
@slfan2013 I should probably also mention that with the latest docker Image on quay.io now supports HTTP content-negotiation. You can specify the format you want in an HTTP Accept header as show below:
```shell
$ docker pull quay.io/plotly/orca
$ docker run -it -d -p 9091:9091 quay.io/plotly/orca
$ curl -d @14.json -H "accept: image/svg+xml" localhost:9091
... return SVG ...
```
The supported accept types are given by the values in the object below:
https://github.com/plotly/orca/blob/f40962271ce901492513115854cceb45977448eb/src/component/plotly-graph/constants.js#L2-L10

**Comment by slfan2013** [comment]
Thank you @antoinerg . It helped a lot!

Now I am able to generate the plot. How can I export it (possibly using a correct endpoint)?

What I have done using `R` is as follows, 

```
pacman::p_load(plotly, httr, jsonlite)
plot = plot_ly(z = ~volcano) %>% add_surface()
bod = list(
  figure = plotly_build(plot)$x[c("data","layout")],
  format = 'svg'
)
POST(url = "http://localhost:9091", body = plotly:::to_JSON(bod), encode = "json")
```

It successfully generated the plot giving an output of 
```
Response [http://localhost:9091/]
  Date: 2019-07-26 18:21
  Status: 200
  Content-Type: image/svg+xml
  Size: 309 kB
<BINARY BODY>
```

I wonder how am I suppose to download this? Something like `http://localhost:9091/xxx.svg`?

**Comment by slfan2013** [comment]
Oh, got it! 

```

res <- httr::POST(
        paste0("http://127.0.0.1:", port), 
        body = to_JSON(bod)
      )
      httr::stop_for_status(res)
      httr::warn_for_status(res)
      con <- httr::content(res, as = "raw")
      writeBin(con, file)
```

Perfect. This plotly + orca whole thing is perfect. Thank you @antoinerg
