### ISSUE TITLE
Scatter Box Map Plot Error 525

### ISSUE THREAD

**Issue by skuzmier** [plotly/orca#193]
When I try to save a map box scatter plot as a .png using pio.write_image(fig)
```
ValueError: 
The image request was rejected by the orca conversion utility
with the following error:
   525: plotly.js error
```
When I generate an interactive plot everything works fine and when I save the image manually it looks like this.

![image](https://user-images.githubusercontent.com/12565852/51658157-2726ce00-1f75-11e9-880f-b788dad7a08f.png)

The plot is created using the following function:
```
def plot_caiso_map(df, dt, col):
    #set the geo=spatial data
    if 'ldt' not in df.columns:
        df.reset_index(inplace=True)
    df.set_index('ldt', inplace=True)
    df['hover_info'] =  df['node'] +  '  |  ' +df[col].round(2).astype(str)
    df = df[dt[0]: dt[0]]
    data = [go.Scattermapbox(
            lat= df['lat'] ,
            lon= df['long'],
            customdata = df['node'],
            mode='markers',
            marker=dict(
                size= 6,
                color= df[col],
                colorscale= 'Jet',
                showscale=True,
                cmax= min(200, max(df[col].max(), 100)),
                cmin= max(-40, min(df[col].min(), -20)),
                opacity = .8,
            ),
        #text = df['hover_info'],
          )]
    #set the layout to plot
    layout = go.Layout(autosize=False,
                   mapbox= dict(accesstoken='MY_TOKEN',
                                bearing=0,
                                pitch=0,
                                zoom=5,
                                center= dict(lat=36.95,
                                             lon=-117.0),
                                style='dark'),
                    width=900,
                    height=700, 
                    title = "CAISO %s - %s" %(col.upper(), dt))
    df.reset_index(inplace=True)
    fig =  go.FigureWidget(data=data, 
                     layout=layout
                    )
    pio.write_image(fig, 'prices_map.png')
    py.iplot(fig)
    return fig

```
This issue may be related to issue #188  but the error messages were different enough that I though this might be seperate. 

If I try saving the figure to JSON and then running from command line with:

orca graph figure.json --mapbox-access-token MY_ACCESS_TOKEN  -o figure.png --verbose
I get the following error message:

```
gpu process crashed - false
          Chrome version 59.0.3071.115
          Electron version 1.8.4
gpu process crashed - false
          Chrome version 59.0.3071.115
          Electron version 1.8.4
gpu process crashed - false
          Chrome version 59.0.3071.115
          Electron version 1.8.4
gpu process crashed - false
          Chrome version 59.0.3071.115
          Electron version 1.8.4
gpu process crashed - false
          Chrome version 59.0.3071.115
          Electron version 1.8.4
export error 525 for figure - plotly.js error
  {"message":"Cannot read property 'resize' of undefined","name":"TypeError"}
```

I am running plotly 3.5.0 on a remote Ubuntu 18 server with x11 installed.

orca configuration
------------------
    executable: orca
    port: None
    timeout: None
    default_width: None
    default_height: None
    default_scale: 1
    default_format: png
    mathjax: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js
    topojson: None
    mapbox_access_token: pk.eyJ1Ijoic2t1em1pZXIxIiwiYSI6ImNqbmptM3BtMDAyeHQzcXF0Z2V0b211dnUifQ.wnok9oJprkw0eALpRqq_9w

constants
---------
    plotlyjs: /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/plotly/package_data/plotly.min.js 
    config_file: /home/ubuntu/.plotly/.orca

**Comment by etpinard** [comment]
Thanks for writing in!

1. Can you try exporting a `scattermapbox` graph with only a few data points to see if that works?
1. Can you share your `lon` and `lat` data array with us to help us debug? If not, could tell us how many data points you're trying to plot?

**Comment by skuzmier** [comment]
Tham you for your prompt response and assistance with this awesome library. I was trying to plot ~2000 data points. I have tried reducing this to 10 data points and am still running into the same issue. When I export it as a JSON and the file looks like the following:

```
{
  "data": [
    {
      "customdata": [
        "ALAMT2G_7_N002",
        "ALAMT6G_7_B1",
        "ALTA31GT_7_B1",
        "ALTAD1_7_N006",
        "ARVIN_6_N001",
        "ASH_6_N005",
        "AVSOLAR_7_N008",
        "BAYWOOD_6_N001",
        "BELRIDGE_1_N001",
        "BORDER_6_N008"
      ],
      "lat": [
        33.7714151734996,
        33.7716868552252,
        34.87,
        35.0383489999876,
        35.1504459680479,
        33.1365163430307,
        34.789501,
        35.3601765947686,
        35.4557223183807,
        32.5662537052904
      ],
      "lon": [
        -118.100670984251,
        -118.100876057291,
        -116.88,
        -118.292711891128,
        -118.878813580666,
        -117.070398917774,
        -118.431381,
        -120.811564365732,
        -119.631902781825,
        -116.944333351687
      ],
      "marker": {
        "cmax": 100,
        "cmin": -20,
        "color": [
          3.31096005439758,
          3.31096005439758,
          0.0,
          0.0,
          0.0,
          36.8146781921387,
          0.0,
          0.0,
          0.0,
          45.6439018249512
        ],
        "colorscale": "Jet",
        "opacity": 0.8,
        "showscale": true,
        "size": 6
      },
      "mode": "markers",
      "text": [
        "ALAMT2G_7_N002  |  3.31",
        "ALAMT6G_7_B1  |  3.31",
        "ALTA31GT_7_B1  |  0.0",
        "ALTAD1_7_N006  |  0.0",
        "ARVIN_6_N001  |  0.0",
        "ASH_6_N005  |  36.81",
        "AVSOLAR_7_N008  |  0.0",
        "BAYWOOD_6_N001  |  0.0",
        "BELRIDGE_1_N001  |  0.0",
        "BORDER_6_N008  |  45.64"
      ],
      "type": "scattermapbox"
    }
  ],
  "layout": {
    "autosize": false,
    "height": 700,
    "mapbox": {
      "accesstoken": "MY_TOKEN",
      "bearing": 0,
      "center": {
        "lat": 36.95,
        "lon": -117.0
      },
      "pitch": 0,
      "style": "dark",
      "zoom": 5
    },
    "title": {
      "text": "CAISO RT_CONGESTION - ['03-15-2017 11:45:00']"
    },
    "width": 900
  }
```

**Comment by etpinard** [comment]
Thanks very much for the report @skuzmier !

Turns out our logic was wrong for mapbox access tokens stored inside `layout.mapbox`. Things work ok when you pass the access token as a config option.

We'll have a fix for this out soon.

**Comment by skuzmier** [comment]
This may be an obvious thing, but how do I pass it as a config option?
I appreciate you looking into this for me.

**Comment by etpinard** [comment]
Looks like there's a way from the python api:

```
 plotly.io.orca.config.mapbox_access_token = "your token"
```

should do the trick.

More info here -> https://plot.ly/python/orca-management/

**Comment by skuzmier** [comment]
I have upgraded to the latest version of orca 1.2.1 and still, and it appears the issue may be deeper than the mapbox token problem. 
```gpu process crashed - false
          Chrome version 59.0.3071.115
          Electron version 1.8.4
gpu process crashed - false
          Chrome version 59.0.3071.115
          Electron version 1.8.4
gpu process crashed - false
          Chrome version 59.0.3071.115
          Electron version 1.8.4
gpu process crashed - false
          Chrome version 59.0.3071.115
          Electron version 1.8.4
gpu process crashed - false
          Chrome version 59.0.3071.115
          Electron version 1.8.4
export error 525 for figure - plotly.js error
  {"message":"Cannot read property 'resize' of undefined","name":"TypeError"} ```

 The issue appears to be something unique to running on a headless ubuntu server as the code works correctly when run locally on my mac.  So far I have tried plot with and without the mapbox token passed in the JSON file, having set it as an orca config option with no effect.  I have also attempted installing using both the Anaconda install method as well as the AppImage. I have also attempted running it using both X11 and Xvfb. Image exports for standard scatter, and line plots work correctly on the server. 

Please let me know if there is any other information I can provide you with that would be helpful.

**Comment by etpinard** [comment]
> The issue appears to be something unique to running on a headless ubuntu server a

A few things to read / try:

- https://github.com/plotly/orca#linux-troubleshooting-cannot-open-shared-object
- https://github.com/plotly/orca#linux-troubleshooting-headless-server-configuration
- https://github.com/plotly/orca/issues/127#issuecomment-426847504

**Comment by skuzmier** [comment]
I appreciate you sending over those links. I tried the first two last night and have tried again today.

I can replicate and resolve the issue referenced in 
* https://github.com/plotly/orca#linux-troubleshooting-cannot-open-shared-object
by not having Xvfb or X11 working, and correctly resolve it.

I am able to successfully run both of the tests described in the quickstart section for troubleshooting headless server configuration. 

For issue 127 I am not certian that I have implemented the suggested recomendation correctly but the command I am using is:


``` 
orca graph prices.json --enable-webgl --format png -o prices.png --verbose
```
my symlink invoking orca is

```
#!/bin/bash
xvfb-run -a  /home/ubuntu/orca/orca-1.2.1-x86_64.AppImage "$@"
```

I can sucessfully run
```
fig = {"data": [{"y": [1,2,1]}]}
call(['orca', 'graph', json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder), '--enable-webgl'])
```

I have attempted to install using the docker file but ran into errors, which I didn't record, and may be my fault as this is my first time using docker. I am trying a docker install again to see if that can fix the issue.
