### ISSUE TITLE
orca not found on path using conda install

### ISSUE THREAD

**Issue by TiemenSch** [plotly/orca#202]
I just tried to install orca using the conda installation method on Windows 10 using Miniconda. Python version is 3.6.6 and the installed orca version is 1.2.0. E.g., I did:
``conda install -c plotly plotly-orca``

It installs fine, but does not put the executable on path nor in the Scripts folder of the environment. A quick search also reveals no executable file called orca (only some ``orca.py`` files inside the package).

``npm install -g electron@1.8.4 orca`` worked fine though (orca found on path afterwards) and also installs version 1.2.0.

**Comment by etpinard** [comment]
Should be fixed now for `orca@1.2.1`.

Would you mind giving:

```
conda install -c plotly plotly-orca
```

another shot?

**Comment by TiemenSch** [comment]
Done. It works!
