### ISSUE TITLE
Intermittent Orca build failure due to --recv-keys failure

### ISSUE THREAD

**Issue by scjody** [plotly/orca#209]
https://github.com/plotly/orca/pull/197 attempted to fix the Docker build run by CI (`docker-build-and-push` step) but the build still fails frequently (>75% of the time) with:

```
Step 4/23 : RUN set -ex   && for key in     9554F04D7259F04124DE6B476D5A82AC7E37093B     94AE36675C464D64BAFA68DD7434390BDBE9B9C5     FD3A5288F042B6850C66B31F09FE44734EB7990E     71DCFD284A79C3B38668286BC97EC7A07EDE3FC1     DD8F2338BAE7501E3DD5AC78C273792F7D83545D     B9AE9905FFD7803F25714661B63B535A4C206CA9     C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8     56730D5401028683275BD23C23EFEFE93C4CFFFE   ; do     gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key" ;   done
 ---> Running in 73e9550ab7db
+ gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 9554F04D7259F04124DE6B476D5A82AC7E37093B
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: requesting key 7E37093B from hkp server ha.pool.sks-keyservers.net
gpgkeys: key 9554F04D7259F04124DE6B476D5A82AC7E37093B can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper general error
gpg: keyserver communications error: unknown pubkey algorithm
gpg: keyserver receive failed: unknown pubkey algorithm
```

When it fails it generally fails on the key shown above (the first one we attempt to retrieve), but I've seen it fail on other keys about 10% of the time.

@plotly/devops @antoinerg @etpinard FYI

**Comment by antoinerg** [comment]
The only reason we're downloading those keys is to install `nodejs`. Maybe we could simply start with a Docker image already containing `nodejs`.

@plotly/devops Is it mandatory to base our image from `ubuntu:xenial`?

**Comment by scjody** [comment]
@antoinerg It's not mandatory. The big reason to use Ubuntu is that it's what the team has the most familiarity with, but there are many [official node images](https://hub.docker.com/_/node/) based on Debian, which is pretty close.

I'd be concerned about fonts being different / not existing with Debian, but that's easy enough to tes for.

**Comment by jkaplowitz** [comment]
@scjody I'm at least pretty familiar with Debian from my non-Plotly life, so I can help if needed ... but the vast majority of font packages in Ubuntu, like 99% of the rest of Ubuntu, come from Debian. Like you, I'm not very worried.

**Comment by antoinerg** [comment]
Maybe we could start from `ubuntu:bionic` (Ubuntu LTS 18.04) and do `apt-get install nodejs`. We would then end up with `nodejs v8.10.0`.

**Comment by scjody** [comment]
We're on 6.11.3 now, so that's a big change, but if you want to go for it that's fine with me.
