### ISSUE TITLE
Distributing this thing

### ISSUE THREAD

**Issue by etpinard** [plotly/orca#21]
On top of the `@plotly/image-exporter` npm package , we'll add standalone Mac, Linux and Window binaries to the release [section](https://github.com/plotly/image-exporter/releases) after every release similar to what's done currently in [plotly-database-connector](https://github.com/plotly/plotly-database-connector/releases). 

Standalone binaries ship with node.js and electron bundled up, but without the fonts we use on prod (if users want the fonts, they'll have to install them locally or use docker). We'll probably use [`electron-packager`](https://www.christianengvall.se/electron-packager-tutorial/) same as plotly-database-connector for this task, although there are other options. This part is easy.

Now, we need to figure how to distribute `image-exporter` to python and R API users. We'll also need to write (thin) python and R wrapper around the [`plotly-graph-exporter`](https://github.com/plotly/image-exporter/blob/master/bin/plotly-graph-exporter.js) CLI command e.g in python:

```py
from subprocess import call
import json

fig = {"data": [{"y": [1,2,1]}]}
call(['plotly-graph-exporter', json.dumps(fig)])
```

For distributing, I can think of three different options:

1) Include the `image-exporter` standalone binaries in plotly.py and plotly.R packages and write the wrapper there, similar to what we currently do with the plotly.js bundle for offline. Potential problems, we'll have to make platform-dependent installs - is that possible with pip and CRAN? Download times might increase significantly too.
1) Make new `plotly-image-exporter` py/pip and R/CRAN packages from this repo - which would include the py/R wrappers. This option would require platform-specific install too.
1) Make users download and install the standalone binaries from this repo's release [section](https://github.com/plotly/image-exporter/releases), add wrapper code to `plotly.py` and `plotly.R` and make them spit out errors if called when `plotly-graph-exporter` isn't installed.

cc @chriddyp @cpsievert @jackparmer

**Comment by jmmease** [comment]
Quick thought regarding packing this for python users.

`poppler` and `nodejs` are both available in the [main](https://repo.continuum.io/pkgs/main/linux-64/) conda repository (at least for linux and os x, poppler actually isn't available in the window repo).  I wonder if it would be feasible (sensible?) to create a conda package that has dependecies on `nodejs` and `poppler` and basically just contains the `bin/`, `src/`, and `node_modules/` directories from this repo, plus a thin python subprocess wrapper around `plotly-graph-exporter.js`.

cc @jackparmer @chriddyp

**Comment by jackparmer** [comment]
>  I wonder if it would be feasible (sensible?) to create a conda package that has dependecies on nodejs and poppler and basically just contains the bin/, src/, and node_modules/ directories from this repo, plus a thin python subprocess wrapper around plotly-graph-exporter.js.

I'm all for this as long as we can get to a point where we feel it works in a bulletproof way. Otherwise be prepared for hundreds of plotly.py user complaints/issues on GitHub and the forum 😬

**Comment by etpinard** [comment]
To note, we only need `poppler` for eps exports. Not sure what percentage of python users export in eps, but I suspect it is small.

**Comment by jmmease** [comment]
@JamesCropcho That's certainly reasonable :-) What would be your preferred approach for local installation?  Is it currently possible to create standalone binaries?  I don't see anything in https://github.com/plotly/image-exporter/releases and I don't know enough about electron to build them myself from the repo.

**Comment by JamesCropcho** [comment]
@jmmease Local installation is actually being figured out and implemented by Plotly and me very actively right now. Hopefully this will be soon possible for Plotly users.

**Comment by etpinard** [comment]
from @jackparmer 

![image](https://user-images.githubusercontent.com/6675409/39130695-bcc0b3ea-46db-11e8-8d3a-ced29cf23952.png)

**Comment by jackparmer** [comment]
@cpetzold and NPM support very kindly helped us acquire the NPM package name `orca`. 🙇 https://www.npmjs.com/package/orca is owned by NPM user `plotly` now.

![image](https://user-images.githubusercontent.com/1865834/39202678-9e88c99a-47c0-11e8-9db0-ce4d52b19d0c.png)

**Comment by etpinard** [comment]
... oh and RE https://github.com/plotly/image-exporter/issues/21#issuecomment-384008872, yes we should make our first release `v1.0.0`.

**Comment by JamesCropcho** [comment]
> yes we should make our first release v1.0.0.

Okay, I have done so, in #82: https://github.com/plotly/orca/pull/82/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by etpinard** [comment]
Orca v1.0.0 is out:

- https://github.com/plotly/orca/releases/tag/v1.0.0
- https://www.npmjs.com/package/orca

Please see the installations instructions [here](https://github.com/plotly/orca#installation).

Our release process is far from perfect, but good enough I'd say to close this issue closed.

**Comment by mungojam** [comment]
It would be useful for my workplace if this was bundled in a python package as we don't currently have a good internal way to distribute anything else like node packages as we are python focused. You can make OS dependent wheel files as other projects do
