### ISSUE TITLE
Orca requires a Mapbox API token for .png file generation

### ISSUE THREAD

**Issue by ha5dzs** [plotly/orca#227]
Hi,

Using Mac (Mojave 10.14.4), RStudio (1.2.1335), Plotly (4.8.0)  

I am trying to create a png from a 'histogram' and 'histogram2d'  plotly object. I found that it only works if I have a Mapbox token. It doesn't matter if I install Orca using npm or manually. 

Is this normal?

**Comment by etpinard** [comment]
You should only need to set a mapbox access token to export mapbox graphs.

This must be a problem with the R api. I suggest filling an issue over on https://github.com/ropensci/plotly

Thank you!

**Comment by ha5dzs** [comment]
Okay, thanks!
