### ISSUE TITLE
Assertion bug

### ISSUE THREAD

**Issue by rhodotherm** [plotly/orca#229]
I use orca to export plot_ly graphs to svg from RStudio. This assertion problem keeps appearing (thus orca failing):
This is what I get from the RStudio console:
> orca(p, "r-susragpairs.svg", widht = 1000)
Error: The orca command-line utility is required for this functionality.

Please follow the installation instructions here -- https://github.com/plotly/orca#installation

But although I followed all the installation steps, this is what I get from orca --help:
(xenial)user@localhost:~$ orca --help

(orca:22130): GLib-GIO-CRITICAL **: g_dbus_connection_register_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(orca:22130): GLib-GIO-CRITICAL **: g_dbus_connection_register_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(orca:22130): GLib-GIO-CRITICAL **: g_dbus_connection_get_unique_name: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
Plotly's image-exporting utilities

Usage: orca [--version] [--help] <command> [<args>]

Available commands:
- graph [or plotly-graph, plotly_graph]
Generates an image of plotly graph from inputted plotly.js JSON attributes.
For more info, run `orca graph --help`.
- serve [or server]
Boots up a server with one route per available export component
For more info, run `orca serve --help`.

I managed to export one graph after updating all RSrudio packages, but it failed again with next one. Also tried to kill orca processes. Updated and upgraded my installation... nothing works.

**Comment by rhodotherm** [comment]
Hello, the problem was fixed following instruction on issue #120.
https://github.com/plotly/orca/issues/120#issuecomment-424000634
Had to edit R's path to environment variable. In my case:
> Sys.setenv("PATH" = paste(Sys.getenv("PATH"), "/home/user/miniconda2/bin/", sep = .Platform$path.sep))

Sorry for the inconveniences
Raul

**Comment by dplazas** [comment]
hi, I followed all suggestions... "orca" appears now in my Rstudio but doing this "
p <- plot_ly(x = 1:10, y = 1:10, color = 1:10)
orca(p, "plot.svg")
I still obtain this error :
Error: The orca command-line utility is required for this functionality.
what else can I do?? I tried many things... if nothing works I ll go back to my old software... 
thanks

**Comment by antoinerg** [comment]
Hello @dplazas,

what operating system are you running? It looks like you don't have `orca` as a command-line utility available in your path. Can you run `orca` from the command line?
