### ISSUE TITLE
"Segmentation fault (core dumped)" when executing "orca --help"

### ISSUE THREAD

**Issue by ealashwali** [plotly/orca#246]
I am using Ubuntu 18.04. I need to install orca in Ubuntu. 

After I downloaded: orca-1.2.1-x86_64.AppImage, into the `Downloads` directory, I performed the following commands:
```
sudo chmod +x orca-1.2.1-x86_64.AppImage
ln -s /home/e/Downloads/orca-1.2.1-x86_64.AppImage /home/me/.local/lib/python3.6/site-packages/orca
```

But when I execute:
`which orca`
I do not find anything printed in the terminal. But there is a file named `orca `created at the `/home/me/.local/lib/python3.6/site-packages/`

Then when I execute: orca --help, I get:
`Segmentation fault (core dumped)`

Can you please help me identify the problem?

**Comment by ealashwali** [comment]
Now it is partially working. It turns that first I have to find the right PATH value by executing: 
`echo $PATH ` It may be helpful if you can add this in the instructions. 

But now, when I execute: 
`orca --help`

I get:
```
Gtk-Message: 11:58:45.142: Failed to load module "canberra-gtk-module"
Plotly's image-exporting utilities

  Usage: orca [--version] [--help] <command> [<args>]
.... 

Any idea what should be done here?
```

**Comment by antoinerg** [comment]
@ealashwali Can you try installing all the dependencies? Installing `chromium` will most probably get you everything you need.
