### ISSUE TITLE
EPS: should preserve graphics in vector format and not rasterize

### ISSUE THREAD

**Issue by antoinerg** [plotly/orca#248]
At the moment, opening EPS files produced by Orca in either Illustrator or Inkscape show raster graphics rather than a vector graphics. Zooming in shows that it is pixelated:
![image (5)](https://user-images.githubusercontent.com/301546/65342529-f00aca00-dba0-11e9-8c47-559ebb122911.png)

**Comment by antoinerg** [comment]
The issue is partially fixed in my branch `pr-bump-electron-6` which upgrades electron from v1 to v6 and ships a much newer version of Chromium.

This can be seen for example in the updated [baseline/29.eps](https://github.com/plotly/orca/blob/pr-bump-electron-6/test/image/baselines/29.eps) from that branch which isn't pixelated when zooming in.

However, because EPS does not support semi-transparency, it seems like `poppler` will rasterize graphics if they have semi-transparent elements (ie. elements with opacity `]0,1[` like [the markers in mock 14.json from plotly.js](https://github.com/plotly/plotly.js/blob/master/test/image/mocks/14.json)). The fix is to remove semi-transparency from the figures prior to conversion (as we do for EMF). It might make sense to perform this cleanup in plotly.js itself where we have the full power of d3 selection.

cc @nicolaskruchten

**Comment by Koushikphy** [comment]
I'm facing this issue, eps gets pixelated. Also when you convert the generated `eps` to make `pdf` using `epspdf`, the pixelated/aliasing remains in the generated `pdf`s too
