### ISSUE TITLE
can i use orca in centos 6.8?

### ISSUE THREAD

**Issue by gyodukoo** [plotly/orca#249]
hello
first of all, really thank you for making this.

I would like to know that I can use orca in centos 6.8.

I tried to use AppImage, but it says that some libraries need to be installed such as glibc and so on.
However, in my company we cannot install that kinds of library on our linux server.

Is there any way to use orca in centos 6.8 without those libraries?

Thanks in advance.

**Comment by antoinerg** [comment]
@gyodukoo I'm afraid you'll need the dependencies requires to run a Chromium browser (which is what Orca runs under the hood). If your server runs Docker, it would be very much simpler to use that instead.

**Comment by antoinerg** [comment]
> I'm afraid you'll need the dependencies required to run a Chromium browser (which is what Orca runs under the hood).

Although running Orca in centos is entirely possible, one will need all the dependencies necessary to run a Chromium browser.
