### ISSUE TITLE
Windows Subsystem for Linux error-- cannot communicate with local orca server process even though server process seems to be running

### ISSUE THREAD

**Issue by schlich** [plotly/orca#256]
Hello all,

I am trying to write an image to .svg format using a jupyterlab setup on Windows Subsystem for Linux (WSL).  After installing gtk library, installing Xming, configuring env variable DISPLAY=:0, and disabling chrome sandbox, I am still running into issues.  Right now, I'm getting the following error output in my python terminal:

```
For some reason plotly.py was unable to communicate with the
local orca server process, even though the server process seems to be running.

Please review the process and connection information below:

orca status
-----------
    state: running
    executable: /usr/bin/xvfb-run --auto-servernum --server-args -screen 0 640x480x24 +extension RANDR +extension GLX /usr/bin/orca
    version: 1.2.1
    port: 60427
    pid: 29156
    command: ['/usr/bin/xvfb-run', '--auto-servernum', '--server-args', '-screen 0 640x480x24 +extension RANDR +extension GLX', '/usr/bin/orca', 'serve', '-p', '60427', '--plotly', '/home/tyler/.local/share/virtualenvs/thesis-WAlznkOk/lib/python3.7/site-packages/plotly/package_data/plotly.min.js', '--graph-only', '--mathjax', 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js']
```

Any pieces of advice?  Other than examining the server connection, which i'm not entirely sure what is meant by that, I'm wondering if there are any other WSL-compatibility shortcuts i might be able to take.  It would be great if this library could include additional documentation/support for WSL

**Comment by schlich** [comment]
closing for now while i troubleshoot... somehow missed a whole subsection of linux troubleshooting in the readme heh

**Comment by antoinerg** [comment]
Trying to get Orca to work on Windows Subsystem for Linux is rather brave @schlich :sweat_smile:! Please let us know if you succeed. 

I also want to point out that Orca can be installed on Windows and isn't a Linux only product.

**Comment by schlich** [comment]
I did end up getting it working!  it took a lot of cobbling together and trying different things and reinstalling npm about 5 different times but I got there!  Went with Xming and had to disable xvbf.   

My mac died a few days ago and I had to flip a coin as to where to port all my work ended up going with WSL.   Definitely getting a few lessons in technical expertise!

**Comment by raulf2012** [comment]
@schlich can you care to elaborate anymore on the steps you took to get orca to work on WSL?

This has been something that I've been struggling with for some time now and it would be really valuable to get this to work for me

Thus far I've just setup a separate computer with Ubuntu to export my plots to pdf/svg, far from ideal

**Comment by schlich** [comment]
Happy to help, could you outline the steps you've taken and any errors you're getting?

**Comment by raulf2012** [comment]
Thanks @schlich

My attempts have pretty much been limited to installation with conda
Attempting to write a `.pdf` file in a python script results in a generic error associated with orca not being installed (attached below)
[plotly_python_orca_err.txt](https://github.com/plotly/orca/files/3996438/plotly_python_orca_err.txt)

Furthermore, there doesn't seem to be an orca executable installed via this route in the bin location that it should be located

So it seems that the conda installation procedure is a no-go, but it seems to me that you used the npm installation instructions so I'll give that a shot now.

**Comment by raulf2012** [comment]
Wow I can't believe it, I got it to work

My steps:
1. Install conda/anaconda (instructions available elsewhere)
2. Install nodejs (npm) through conda
  - `conda install -c conda-forge nodejs`
3. Install orca through npm via instructions on orca's README
  - `npm install -g electron@1.8.4 orca`
4. Finally, I needed to install a library because of the missing shared `libgconf-2.so.4` library
  - `sudo apt-get install libgconf-2-4`

After these steps, attempting to perform a `fig.write_image("figure.pdf")` worked properly!

@schlich I'm a bit puzzled by your initial comments on this thread:
>After installing gtk library, installing Xming, configuring env variable DISPLAY=:0, and disabling chrome sandbox, I am still running into issues

I didn't really have to mess around with any of this, I do already have Xming setup properly but the gtk library and chrome sandbox bits are unfamiliar to me

If anybody else can try to confirm the procedure I outlined above and let everybody know if it works that would be great

**Comment by badain** [comment]
Just tried here and can confirm your procedure works @raulf2012!

Some aditional missing shared libraries had to be installed:
`sudo apt-get install libgtk2.0-0`
`sudo apt-get install libnss3-dev `

Thanks for sharing!

**Comment by schlich** [comment]
Not sure which dependency changed but it looks like we now need 
`sudo apt-get install libgtk-3-0` 
which may or may not be taking the place of libgtk2.0-0

**Comment by antoinerg** [comment]
I just want to mention that we're basically replacing Orca with the new Kaleido project (https://github.com/plotly/Kaleido) which is significantly easier to install in docker containers and is our new recommended way forward for this kind of thing :)
