### ISSUE TITLE
Accessing Orca deployment from JupyterLab on K8s

### ISSUE THREAD

**Issue by TiemenSch** [plotly/orca#258]
I have a question regarding the accessing of the Orca server using ``plotly.io`` when it's ran as a separate deployment on a Kubernetes setup. How would you typically configure the communication from any typical "singleuser" notebook to the externally running Orca server?

Context:
I'm currently working on a Kubernetes deployment of JupyterLab using the [Zero-to-JupyterHub](https://zero-to-jupyterhub.readthedocs.io/en/latest/) guide. Running plotly orca in a separate deployment would reduce the singleuser image size and complexity quite a bit and keep things neatly compartmentalized. Otherwise each and every singleuser container would contain a complete xvfb install!

**Comment by antoinerg** [comment]
You're right that getting Orca running on a headless system can be tricky and it is much simpler/cleaner to have it run in its own container.

I'm not familiar with our tools in JupyterLab at the moment so I don't know how to call an externally running Orca server but I imagine it should be simple to do.

@jonmmease @nicolaskruchten can you please answer this one?

**Comment by jonmmease** [comment]
Unfortunately, this isn't supported in plotly.py yet. See https://github.com/plotly/plotly.py/issues/1570 for more info.

**Comment by antoinerg** [comment]
@TiemenSch it will be possible to call an externally running Orca in the next release of plotly.py. See PR https://github.com/plotly/plotly.py/pull/1850 for details!
