### ISSUE TITLE
Return code 1: the input device is not a TTY

### ISSUE THREAD

**Issue by fthalabi** [plotly/orca#277]
Hi, I'm having troubles using the docker image of Orca with Jupyterlab.

Relevant outputs: 

`pio.write_image(fig, save_folder+'categorias_paralelas.pdf',format='pdf')`

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-d5e69f7f9ba7> in <module>
----> 1 pio.write_image(fig, save_folder+'categorias_paralelas.pdf',format='pdf')

~/.local/lib64/python3.6/site-packages/plotly/io/_orca.py in write_image(fig, file, format, scale, width, height, validate)
   1765     # Do this first so we don't create a file if image conversion fails
   1766     img_data = to_image(
-> 1767         fig, format=format, scale=scale, width=width, height=height, validate=validate
   1768     )
   1769 

~/.local/lib64/python3.6/site-packages/plotly/io/_orca.py in to_image(fig, format, width, height, scale, validate)
   1530     # Make sure orca sever is running
   1531     # -------------------------------
-> 1532     ensure_server()
   1533 
   1534     # Handle defaults

~/.local/lib64/python3.6/site-packages/plotly/io/_orca.py in ensure_server()
   1388         # Validate orca executable only if server_url is not provided
   1389         if status.state == "unvalidated":
-> 1390             validate_executable()
   1391         # Acquire lock to make sure that we keep the properties of orca_state
   1392         # consistent across threads

~/.local/lib64/python3.6/site-packages/plotly/io/_orca.py in validate_executable()
   1182 for more info on Xvfb
   1183 """
-> 1184         raise ValueError(err_msg)
   1185 
   1186     if not help_result:

ValueError: 
The orca executable is required in order to export figures as static images,
but the executable that was found at '/home/fenho/.local/bin/orca'
does not seem to be a valid plotly orca executable. Please refer to the end of
this message for details on what went wrong.

If you haven't installed orca yet, you can do so using conda as follows:

    $ conda install -c plotly plotly-orca

Alternatively, see other installation methods in the orca project README at
https://github.com/plotly/orca

After installation is complete, no further configuration should be needed.

If you have installed orca, then for some reason plotly.py was unable to
locate it. In this case, set the `plotly.io.orca.config.executable`
property to the full path of your orca executable. For example:

    >>> plotly.io.orca.config.executable = '/path/to/orca'

After updating this executable property, try the export operation again.
If it is successful then you may want to save this configuration so that it
will be applied automatically in future sessions. You can do this as follows:

    >>> plotly.io.orca.config.save()

If you're still having trouble, feel free to ask for help on the forums at
https://community.plot.ly/c/api/python

Here is the error that was returned by the command
    $ /home/fenho/.local/bin/orca --help

[Return code: 1]
the input device is not a TTY

Note: When used on Linux, orca requires an X11 display server, but none was
detected. Please install Xvfb and configure plotly.py to run orca using Xvfb
as follows:

    >>> import plotly.io as pio
    >>> pio.orca.config.use_xvfb = True
    
You can save this configuration for use in future sessions as follows:

    >>> pio.orca.config.save() 
  
See https://www.x.org/releases/X11R7.6/doc/man/man1/Xvfb.1.xhtml
for more info on Xvfb

------------------------------------------------------------------------------------------------------------

`$ /home/fenho/.local/bin/orca --help`

------------------------------------------------------------------------------------------------------------
Plotly's image-exporting utilities

  Usage: orca [--version] [--help] <command> [<args>]

  Available commands:
  - graph [or plotly-graph, plotly_graph]
    Generates an image of plotly graph from inputted plotly.js JSON attributes.
    For more info, run `orca graph --help`.
  - serve [or server]
    Boots up a server with one route per available export component
    For more info, run `orca serve --help`.

----------------------------------------------------------------------------------------------------------------

`$cat /home/fenho/.local/bin/orca`

----------------------------------------------------------------------------------------------------------------

#!/usr/bin/env bash

DOCKER_IMAGE=quay.io/plotly/orca

if [[ $1 == "--help" || $1 == "--version" || $1 == "graph" || $1 == "serve" ]]; then
    docker run --net=host -it \
      -v "$(pwd)":"$(pwd)" -w "$(pwd)" \
       "$DOCKER_IMAGE" "$@"
else
    echo "Unrecognized orca command. Run \`$0 --help\` for more info"
fi

---------------------------------------------------------------------------------------------------------------------
[pip3_list.txt](https://github.com/plotly/orca/files/4051931/pip3_list.txt)

**Comment by antoinerg** [comment]
Hello @fthalabi !

The problem you are running into stems from Docker not being able to start Orca using the provided script in your environment. A workaround would be to remove `-it` in the `docker run` command. See https://stackoverflow.com/questions/43099116/error-the-input-device-is-not-a-tty for details.

I also realize that the script you are using to start Orca contains a `--net=host` flag which is a Linux-only feature. If you are on Mac or Windows, I expect this to fail. I opened an issue for this specific shortcoming (see https://github.com/plotly/orca/issues/278).

Please let me know if that fixed your problem!

**Comment by fthalabi** [comment]
Thanks @antoinerg , I can confirm that the problem is solved with the given workaround.
