### ISSUE TITLE
Failed to load module "appmenu-gtk-module"

### ISSUE THREAD

**Issue by allefeld** [plotly/orca#284]
I installed `orca` via
~~~
conda install -c plotly plotly-orca
~~~

Running it, I get the message 
~~~
$ orca
Gtk-Message: 20:48:12.453: Failed to load module "appmenu-gtk-module"
Segmentation fault
~~~

On my system (Debian 10.2) there is no package `appmenu-gtk-module`. Instead I tried installing `appmenu-gtk2-module` and `appmenu-gtk-module-common`, with no success.

`chromium` is installed, since it is my default browser.

How do I get orca to run? I need it for PDF export from plotly.

**Comment by allefeld** [comment]
PS: Why does a command-line program that has no UI and is meant to run invisibly in the background have so many dependencies on desktop libraries and need a running X server?

**Comment by antoinerg** [comment]
> On my system (Debian 10.2) there is no package appmenu-gtk-module

Can you please try installing [`appmenu-gtk3-module`](https://packages.debian.org/buster/appmenu-gtk3-module) or [`appmenu-gtk2-module`](https://packages.debian.org/buster/appmenu-gtk2-module) and report here whether it fixed the problem or not?

> PS: Why does a command-line program that has no UI and is meant to run invisibly in the background have so many dependencies on desktop libraries and need a running X server?

@allefeld the reason is that plotly.js was designed for the web first and therefore relies on having a functional browser (a DOM, a WebGL renderer, etc.) to build figures. At the moment, I don't think that running plotly.js outside the browser would be trivial (at least not if we want to support all the different trace types). Therefore, we have to ship a browser, a display server, and all the other dependencies. It is not ideal but that's what it is.

If you have Docker on your Linux machine, I personally recommend running Orca in a Docker container `docker run -p 9091:9091 quay.io/plotly/orca` which is 1) a one-liner and 2) will always work reproducibly.

**Comment by allefeld** [comment]
> Can you please try installing [`appmenu-gtk3-module`](https://packages.debian.org/buster/appmenu-gtk3-module) or [`appmenu-gtk2-module`](https://packages.debian.org/buster/appmenu-gtk2-module) and report here whether it fixed the problem or not?

Installing the gtk2 version gets rid of `Failed to load module "appmenu-gtk-module`. However, the segmentation fault remains. Is there something I can do to help you debug that?

> At the moment, I don't think that running plotly.js outside the browser would be trivial (at least not if we want to support all the different trace types).

No, not plotly. But orca? I run JupyterLab on one computer and access it through a browser on another. The pdf export through orca happens on the server, and it does not involve displaying anything, does it? Or, if it involves a browser, wouldn't it be better to move the export code into the frontend, i.e. the browser I'm using plotly from?

> I personally recommend running Orca in a Docker container

How would I configure plotly so that that happens automatically on the server? Like this?
`plotly.io.orca.config.executable = 'docker run -p 9091:9091 quay.io/plotly/orca'`

**Comment by antoinerg** [comment]
> Installing the gtk2 version gets rid of `Failed to load module "appmenu-gtk-module`. However, the segmentation fault remains. Is there something I can do to help you debug that?

Do you, by any chance, have a `NODE_OPTIONS` environment variable currently set in your env?

> The pdf export through orca happens on the server, and it does not involve displaying anything, does it?

Orca uses a browser which expects a display server to be running. Are you running Orca in a headless environment? If so, try running Orca with a virtual display server `xvfb-run -a orca`.

> Or, if it involves a browser, wouldn't it be better to move the export code into the frontend, i.e. the browser I'm using plotly from?

That's a very interesting idea! Right now, we send to Orca the JSON description of the figure: it then renders it from scratch and converts it into the requested format. If the goal is simply to get PDF/EPS/EMF/PNG out of an already built figure in a browser, there could be a simpler/lighter way to go about it. That's food for thoughts :thinking: 

> How would I configure plotly so that that happens automatically on the server? Like this?
plotly.io.orca.config.executable = 'docker run -p 9091:9091 quay.io/plotly/orca'

I usually: 1) start the docker container running Orca (either prior or via a system command in python) and 2) set `plotly.io.orca.config.server_url` to the URL of my Orca endpoint `http://$HOST:9091/`

**Comment by allefeld** [comment]
> Do you, by any chance, have a `NODE_OPTIONS` environment variable currently set in your env?

Surprisingly, I do: `--max-old-space-size=4096`. I have no idea where that comes from.


> That's food for thoughts

Great!


> I usually: 1) start the docker container running Orca (either prior or via a system command in python) and 2) set `plotly.io.orca.config.server_url` to the URL of my Orca endpoint `http://$HOST:9091/`

OK, got it. I'll try starting the docker image automatically when I start JupyterLab.

**Comment by antoinerg** [comment]
> > Do you, by any chance, have a `NODE_OPTIONS` environment variable currently set in your env?
> 
> Surprisingly, I do: `--max-old-space-size=4096`. I have no idea where that comes from.

I think you're hitting this issue: https://github.com/plotly/orca/issues/124 . Fortunately, it will be fixed in our next minor release. In the meantime, Docker should do the trick! Good luck @allefeld and don't hesitate to come back here to report any problem you may encounter :smile_cat:

**Comment by allefeld** [comment]
Great, thanks a lot!
