### ISSUE TITLE
Can't find the file "orca Setup X.Y.Z" inside the "windows-release.zip" file

### ISSUE THREAD

**Issue by fmgithub2017** [plotly/orca#285]
Please, am I missing something trivial?

I just can't find the file "orca Setup X.Y.Z" inside the "windows-release.zip" file, as described in "Method 4: Standalone binaries" for Windows.

Thank you.

**Comment by antoinerg** [comment]
Hello @fmgithub2017!

If I unzip the following file [v1.2.1/windows-release.zip](https://github.com/plotly/orca/releases/download/v1.2.1/windows-release.zip):
```
$ unzip windows-release.zip
Archive:  windows-release.zip
  inflating: release/orca Setup 1.2.1.exe
```
I do find the file `orca Setup 1.2.1.exe` under the release folder.

**Comment by fmgithub2017** [comment]
Thank you @antoinerg ! 
For the version you referred (1.2.1) there is indeed the orca setup file inside. I will use it then.
However, for versions from 3.0.4 and up I still could not find it. Aren't they not available for Windows?

**Comment by antoinerg** [comment]
> For the version you referred (1.2.1) there is indeed the orca setup file inside. I will use it then.

Great! I will close this issue the.

> However, for versions from 3.0.4 and up I still could not find it. 

About versions 3 and up, those shouldn't exist and I opened an issue to point that out (https://github.com/plotly/orca/issues/286). The latest release really is `v1.2.1`. There are several bug fixes currently on `master` which are not in `v1.2.1` but they will be part of `v1.3.0` which I intend to release very soon. We're sorry about the confusing tag names. This will be resolved shortly.

Thank you @fmgithub2017

**Comment by fmgithub2017** [comment]
Thank you very much for the explanation, @antoinerg .
