### ISSUE TITLE
Orca for R / Windows 10: Provided path to plotly.js bundle does not exist

### ISSUE THREAD

**Issue by guenterhack** [plotly/orca#302]
Hi
I've tried for two days to get Orca running with R and Rstudio Desktop (latest versions) on Windows 10 and I've followed the installation instructions, inserted the Path variable etc.. I have also installed plot.ly via npm and the corresponding libraries (orca and plotly) via R. Plotly works great and orca is reachable via Windows command line. But if I try to export my graph via orca from Rstudio, I get an error message from Orca: A JavaScript error occurred in the main process. Uncaught exception: Error: Provided path to plotly.js bundle does not exist and does not correspond to a release version. 

Where do I tell the Orca binary where to look for the correct version of Plotly? Any help would be greatly appreciated. 
![orca-bug](https://user-images.githubusercontent.com/20581051/77426461-cf802e80-6dd4-11ea-89b7-f2941ea2dd71.jpg)

**Comment by antoinerg** [comment]
Hello @guenterhack,

I haven't used Plotly for R but @rpkyle or @nicolaskruchten may be able to answer your question. Thank you for using Plotly!

**Comment by guenterhack** [comment]
I've tried to run the script from the Windows command line. Everything works fine, but neither orca (npm) nor orca as an exe works. Either R doesn't find orca (npm) or the orca binary (correctly installed, correct PATH variable) throws the error above. How do I tell the binary where to find the correct version of plotly?

**Comment by antoinerg** [comment]
> I've tried to run the script from the Windows command line. Everything works fine

@guenterhack sorry for the late reply. I think you should open an issue over at https://github.com/ropensci/plotly/ (ie. the plotly graphing library for R) considering that your Orca instance does seem to work. I wonder if there is something wrong with how it wraps Orca as someone else has been having issues recently with it (see #306).
