### ISSUE TITLE
Using ORCA on Google Colab

### ISSUE THREAD

**Issue by csrajath** [plotly/orca#363]
How can one install ORCA on Google Colab?

**Comment by antoinerg** [comment]
> How can one install ORCA on Google Colab?

Hello @csrajath ! If you intend to use Orca from Python, you might want to have a look at [plotly/Kaleido](https://github.com/plotly/kaleido) which is much easier to install (most of the time a simple `pip install kaleido` will do)!

I hope it helps!

**Comment by csrajath** [comment]
> > How can one install ORCA on Google Colab?
> 
> Hello @csrajath ! If you intend to use Orca from Python, you might want to have a look at [plotly/Kaleido](https://github.com/plotly/kaleido) which is much easier to install (most of the time a simple `pip install kaleido` will do)!
> 
> I hope it helps!

Thanks!!!
