### ISSUE TITLE
imageserver monitoring & restarts for On-Prem

### ISSUE THREAD

**Issue by scjody** [plotly/orca#45]
Another issue coming out of https://github.com/plotly/streambed/issues/9865#issuecomment-349995119 is that (like the old imageservers) the new ones aren't 100% reliable. For Plotly Cloud, this is OK because Kubernetes performs health checks and will restart any hung pods, but for On-Prem we need a solution.

Existing imageservers are monitored by monit. We can probably use this in the new imageserver container by starting it in the background from the `run_server` script, but that needs to be tested.

@bpostlethwaite @BRONSOLO Do you have any other ideas?

**Comment by antoinerg** [comment]
Closed due to inactivity. Feel free to reopen if necessary.
