### ISSUE TITLE
How to build on Linux?

### ISSUE THREAD

**Issue by JamesCropcho** [plotly/orca#58]
@etpinard:
> Would you mind adding Linux `deb` target so that I can test it on my laptop? (Sorry for the inconvenience if any)

@JamesCropcho:
> I have Ubuntu as the main OS on my laptop, which is a Debian distribution. AppImage is the default format for this build target. If one runs `electron-builder .` or similar, one would get an AppImage which one can execute on Debian.

@etpinard:
> Would you opening up an issue about trying to build this thing for Linux, so that we don't forget about #52 (comment)

I am opening that issue as requested, here.

So as I had stated, we are already building for Linux via the AppImage target. (In fact, I am developing for Plotly on Ubuntu.)

So now, Étienne, to confirm, the AppImage not exactly what you're seeking, and instead the Linux build target should be replaced by `deb` (a Debian package), is that correct? If so, should this issue be left as a placeholder for that, or would you like me to rapidly make that configuration change?

James

**Comment by probonopd** [comment]
Could you please add the AppImage download to https://github.com/plotly/image-exporter/releases?

**Comment by etpinard** [comment]
@JamesCropcho was this issue resolved in https://github.com/plotly/image-exporter/pull/63?

**Comment by JamesCropcho** [comment]
No. However #63 was a dependency to this. Our most likely path to resolving
this is manual Github Release creation.

**Comment by etpinard** [comment]
The AppImage target on https://github.com/plotly/orca/releases will be fine for the first series of release (to be made as soon as https://github.com/plotly/orca/pull/88 is merged). So, closing this thing.
