### ISSUE TITLE
Intermittent errors in circle CI while running integration tests

### ISSUE THREAD

**Issue by tarzzz** [plotly/orca#61]
The integration tests seem to pass on local, but are very volatile on circle CI and fail often.
The situation has deteriorated with adding a new component (hence a new electron window) in: https://github.com/plotly/image-exporter/pull/60

cc: @etpinard ..

**Comment by etpinard** [comment]
thanks for writing this down :writing_hand:

**Comment by tarzzz** [comment]
The integration tests have been disabled in #60 for now.. !!

**Comment by etpinard** [comment]
Followup on https://github.com/plotly/image-exporter/issues/61#issuecomment-377271980

Integration tests have been brought back in https://github.com/plotly/image-exporter/commit/433d619414c92f0c612d399cb72ca9a7b22bc5a0

**Comment by etpinard** [comment]
PR https://github.com/plotly/image-exporter/pull/76 put `npm run test:integration` is 5x retry loop which should help make out CI runs be less intermittent.

Keeping this issue open, as #76 is far from an ideal fix to this issue.

**Comment by etpinard** [comment]
Closing (for now).
