### ISSUE TITLE
Mac installer doesn't install a CLI

### ISSUE THREAD

**Issue by n-riesco** [plotly/orca#90]
I'm opening this issue to discuss solutions to install Orca as a CLI in Mac.

---

At the moment, `electron-builder` creates a DMG installer for Orca in Mac. This DMG installer is actually a [disk image](https://en.wikipedia.org/wiki/Apple_Disk_Image). And, in our case, it contains the app bundle `Plotly Orca.app`.

My understanding is that when a user double-clicks a `.dmg` file, Mac mounts this disk image and prompts the user to drag the disk image onto the `Applications` folder.

This means Orca is installed on `/Applications/Plotly Orca.app`.

To invoke Orca from the command line, we could use [open](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/open.1.html):
```
open -a "/Applications/Plotly Orca.app" [--args arg1 ...]
```

This is rather cumbersome. We could simplify things by moving `open -a "/Applications/Plotly Orca.app" [--args arg1 ...]` into a script (e.g. `/usr/local/bin/plotly-orca`). I've found two ways to do this:

- create `/usr/local/bin/plotly-orca` on first install (see [here](https://github.com/electron-userland/electron-builder/issues/1396#issuecomment-288614061))

- using a [PKG installer](https://www.electron.build/configuration/pkg) and a [postinstall script](http://macinstallers.blogspot.co.uk/2012/07/scripting-in-installer-packages.html) ([not recommended](https://github.com/electron-userland/electron-builder/issues/1396#issuecomment-288631787))

---

Could any of the mac users confirm that `open -a "/Applications/Plotly Orca.app" [--args arg1 ...]` works, please?

---

@JamesCropcho @etpinard @jackparmer what do you think about these options?

**Comment by etpinard** [comment]
> create /usr/local/bin/plotly-orca on first install (see here)

This sounds :ok_hand: to me.

-----

FYI, post https://github.com/plotly/orca/pull/88/commits/a44fc2f8670f17ed31c6e810da624debddf07605, the `.app` file should be named `orca.app` instead of `Plotly Orca.app`.

**Comment by etpinard** [comment]
any progress on this @n-riesco ?

**Comment by n-riesco** [comment]
@etpinard No, I'm sorry. I have to for someone with a mac for testing. Iwon't be able to look into it until tomorrow.

**Comment by etpinard** [comment]
@n-riesco can you try to download https://s3.console.aws.amazon.com/s3/object/image-exporter-travis-artifacts/plotly/orca/394/394.1/mac-release.zip?region=us-east-1&tab=overview ?

**Comment by n-riesco** [comment]
@etpinard No, I can't, because I don't and AWS account.

**Comment by etpinard** [comment]
How do you download the falcon builds then?

**Comment by n-riesco** [comment]
@etpinard I use links like this: https://s3.amazonaws.com/falcon-travis-artifacts/plotly/falcon-sql-client/NNN/NNN.1/mac-release.zip

**Comment by n-riesco** [comment]
@etpinard Is there any way to tell standard that a `return` in the global scope is perfectly *cromulent* in node? or to skip that line?
```
/home/circleci/project/bin/orca_electron.js
  36:5  error  Parsing error: 'return' outside of function

✖ 1 problem
```

**Comment by etpinard** [comment]
@n-riesco and https://s3.amazonaws.com/image-exporter-travis-artifacts/plotly/orca/392/392.1/mac-release.zip doesn't work for you?

**Comment by etpinard** [comment]
> Is there any way to tell standard that a return in the global scope is perfectly cromulent in node? or to skip that line?

you can use `// eslint-disable-next-line`, or replace that `return` with `process.exit(0)`.

**Comment by n-riesco** [comment]
`process.exit(0)` would kill the app before showing the modal window. I'll try later and see if it's an issue with `eslint`'s parse.

**Comment by etpinard** [comment]
yeah `// eslint-disable-next-line` doesn't work for me either.

Would putting the rest of `orca_electron.js` in an `else` be equivalent?
